"""Backwards-compatible façade over the per-domain DB modules.

The DB layer is physically split into base/sources/items/categories/blocked,
but callers still import everything from ``src.db.models``. Re-export
the full public surface here so those imports keep working.
"""
from src.db.base import (
    get_db,
    init_db,
    get_app_setting,
    set_app_setting,
)
from src.db.sources import (
    source_exists,
    add_source,
    get_pending_sources,
    set_source_pending_msg_id,
    set_source_last_message_id,
    rename_source,
    activate_source,
    update_source_url,
    set_source_chat_id,
    find_sources_by_chat_id,
    increment_source_fail_count,
    reset_source_fail_count,
    update_source_status,
    revive_error_rss_sources,
    remove_source,
    get_source,
    get_active_sources,
    get_sources_by_category,
    reassign_source_category,
    place_source_at_bottom,
    set_source_prompt_extra,
    get_silent_sources,
    reorder_source,
)
from src.db.items import (
    is_seen,
    save_item,
    get_unsent_items,
    get_sent_empty_items,
    update_item_classification,
    increment_classify_attempts,
    mark_sent,
    log_digest,
    prune_old_items,
    set_item_embeddings,
    mark_duplicate,
    get_recent_embedded_items,
    get_duplicate_links,
)
from src.db.categories import (
    category_exists,
    get_categories,
    add_category,
    update_category,
    move_sources_to_category,
    delete_sources_by_category,
    remove_category,
    reorder_category,
    bulk_set_category_prompt_extra,
)
from src.db.blocked import (
    get_blocked_words,
    add_blocked_word,
    remove_blocked_word,
    get_categories_for_word,
    link_word_category,
    unlink_word_category,
    get_word_category_map,
)
__all__ = [
    "get_db", "init_db", "get_app_setting", "set_app_setting",
    "source_exists", "add_source", "get_pending_sources", "set_source_pending_msg_id",
    "set_source_last_message_id", "rename_source", "activate_source", "update_source_url",
    "set_source_chat_id", "find_sources_by_chat_id", "increment_source_fail_count",
    "reset_source_fail_count", "update_source_status", "revive_error_rss_sources", "remove_source", "get_source",
    "get_active_sources", "get_sources_by_category", "reassign_source_category",
    "place_source_at_bottom", "set_source_prompt_extra", "get_silent_sources", "reorder_source",
    "is_seen", "save_item", "get_unsent_items", "get_sent_empty_items",
    "update_item_classification", "increment_classify_attempts", "mark_sent", "log_digest",
    "prune_old_items", "set_item_embeddings", "mark_duplicate", "get_recent_embedded_items",
    "get_duplicate_links",
    "category_exists", "get_categories", "add_category", "update_category",
    "move_sources_to_category", "delete_sources_by_category", "remove_category",
    "reorder_category", "bulk_set_category_prompt_extra",
    "get_blocked_words", "add_blocked_word", "remove_blocked_word",
    "get_categories_for_word", "link_word_category", "unlink_word_category", "get_word_category_map",
]
