"""Backwards-compatible façade over the per-domain DB modules.

The DB layer is physically split into base/sources/items/categories/blocked/
radar, but callers still import everything from ``src.db.models``. Re-export
the full public surface here so those imports keep working.
"""
from src.db.base import (
    get_db,
    init_db,
    get_app_setting,
    set_app_setting,
)
from src.db.sources import (
    source_exists,
    add_source,
    get_pending_sources,
    set_source_pending_msg_id,
    set_source_last_message_id,
    rename_source,
    activate_source,
    update_source_url,
    set_source_chat_id,
    find_sources_by_chat_id,
    increment_source_fail_count,
    reset_source_fail_count,
    update_source_status,
    remove_source,
    get_source,
    get_active_sources,
    get_sources_by_category,
    reassign_source_category,
    place_source_at_bottom,
    set_source_prompt_extra,
    get_silent_sources,
    reorder_source,
)
from src.db.items import (
    is_seen,
    save_item,
    get_unsent_items,
    get_sent_empty_items,
    update_item_classification,
    increment_classify_attempts,
    mark_sent,
    log_digest,
    prune_old_items,
)
from src.db.categories import (
    category_exists,
    get_categories,
    add_category,
    update_category,
    move_sources_to_category,
    delete_sources_by_category,
    remove_category,
    reorder_category,
    bulk_set_category_prompt_extra,
)
from src.db.blocked import (
    get_blocked_words,
    add_blocked_word,
    remove_blocked_word,
)
from src.db.radar import (
    get_radar_keywords,
    add_radar_keyword,
    remove_radar_keyword,
    get_radar_chats,
    add_radar_chat,
    remove_radar_chat,
    update_radar_chat_status,
    update_radar_chat_resolved,
    get_radar_blacklist,
    add_radar_blacklist,
    remove_radar_blacklist,
    log_radar_alert,
    get_recent_radar_alerts,
    link_keyword_chat,
    unlink_keyword_chat,
    get_keyword_chat_links,
    get_chats_for_keyword,
    get_keyword_ids_for_chat,
    count_links_for_keyword,
    count_links_for_chat,
    get_silent_radar_chats,
    update_radar_last_message_at,
)

__all__ = [
    "get_db", "init_db", "get_app_setting", "set_app_setting",
    "source_exists", "add_source", "get_pending_sources", "set_source_pending_msg_id",
    "set_source_last_message_id", "rename_source", "activate_source", "update_source_url",
    "set_source_chat_id", "find_sources_by_chat_id", "increment_source_fail_count",
    "reset_source_fail_count", "update_source_status", "remove_source", "get_source",
    "get_active_sources", "get_sources_by_category", "reassign_source_category",
    "place_source_at_bottom", "set_source_prompt_extra", "get_silent_sources", "reorder_source",
    "is_seen", "save_item", "get_unsent_items", "get_sent_empty_items",
    "update_item_classification", "increment_classify_attempts", "mark_sent", "log_digest",
    "prune_old_items",
    "category_exists", "get_categories", "add_category", "update_category",
    "move_sources_to_category", "delete_sources_by_category", "remove_category",
    "reorder_category", "bulk_set_category_prompt_extra",
    "get_blocked_words", "add_blocked_word", "remove_blocked_word",
    "get_radar_keywords", "add_radar_keyword", "remove_radar_keyword", "get_radar_chats",
    "add_radar_chat", "remove_radar_chat", "update_radar_chat_status", "update_radar_chat_resolved",
    "get_radar_blacklist", "add_radar_blacklist", "remove_radar_blacklist", "log_radar_alert",
    "get_recent_radar_alerts", "link_keyword_chat", "unlink_keyword_chat", "get_keyword_chat_links",
    "get_chats_for_keyword", "get_keyword_ids_for_chat", "count_links_for_keyword",
    "count_links_for_chat", "get_silent_radar_chats", "update_radar_last_message_at",
]
